CREATE DATABASE ECOMMERCEYT
GO
USE ECOMMERCEYT;
GO
create table category(
categoryID INT PRIMARY KEY IDENTITY(1,1),categoryNAME VARCHAR(100)NOT NULL,categoryIMAGEURL VARCHAR(MAX),ISACTIVE BIT NOT NULL,CREATEDDATE DATETIME NOT NULL)

create table subcategory(
subcategoryID INT PRIMARY KEY IDENTITY(1,1),subcategoryNAME VARCHAR(100) NOT NULL,categoryId INT FOREIGN KEY REFERENCES CATEGORY (categoryID) ON DELETE CASCADE NOT NULL,ISACTIVE BIT NOT NULL ,CREATEDDATE DATETIME NOT NULL ) 
Create table product(productID INT PRIMARY KEY IDENTITY(1,1),
productNAME VARCHAR(100) NOT NULL,shortdescription VARCHAR(200)NULL,longdescription VARCHAR(max) NULL,
Additionaldescription VARCHAR(max) NULL,price decimal(18,2),Quantity int not null,Size VARCHAR(30) NULL,Color VARCHAR(50) NULL,
companyname VARCHAR(100)NULL,categoryId INT FOREIGN KEY REFERENCES CATEGORY (categoryID) ON DELETE CASCADE NOT NULL,ISACTIVE BIT NOT NULL ,subcategoryId INT NOT NULL,Sold INT NULL,CREATEDDate DATETIME NOT NULL)
CREATE TABLE PRODUCTIMAGES(
ImageID INT PRIMARY KEY IDENTITY(1,1),IMAGEURL VARCHAR(max) NULL,PRODUCTId INT FOREIGN KEY REFERENCES PRODUCT (PRODUCTId) ON DELETE CASCADE NOT NULL,
DefaultImage BIT NULL)
create table Roles(
RoleId INT PRIMARY KEY ,RoleName VARCHAR(50) NOT NULL
)
INSERT INTO Roles VALUES (1,'Admin')
INSERT INTO Roles VALUES (2,'Customer')
Create TABLE Users(
userId INT PRIMARY KEY IDENTITY(1,1),Name VARCHAR(50) NULL,
username VARCHAR(50) NULL,Email VARCHAR(50) NULL,Address VARCHAR(max) NULL,postcode VARCHAR(50) NULL,Password VARCHAR(50) NULL,
ImageUrl VARCHAR(MAX)NULL,RoleId INT FOREIGN KEY REFERENCES Roles (RoleId) ON DELETE CASCADE NOT NULL,
CreatedDate DATETIME not null)

CREATE TABLE PRODUCTReview(
ReviewId INT PRIMARY KEY IDENTITY(1,1),Rating INT NOT NULL,PRODUCTId INT FOREIGN KEY REFERENCES PRODUCT (PRODUCTId) ON DELETE CASCADE NOT NULL,
userId INT FOREIGN KEY REFERENCES Users (userId) ON DELETE CASCADE NOT NULL,
CreatedDate DATETIME NOT NULL
)
CREATE TABLE Wishlist(
Wishlistid INT PRIMARY KEY IDENTITY(1,1),PRODUCTId INT FOREIGN KEY REFERENCES PRODUCT (PRODUCTId) ON DELETE CASCADE NOT NULL,
UserId INT FOREIGN KEY REFERENCES users(UserId)ON DELETE CASCADE NOT NULL)
CREATE TABLE cart(
cartId INT PRIMARY KEY IDENTITY(1,1),PRODUCTId INT FOREIGN KEY REFERENCES PRODUCT (PRODUCTId) ON DELETE CASCADE NOT NULL,
quantity INT null,UserId INT FOREIGN KEY REFERENCES users(UserId)ON DELETE CASCADE NOT NULL,CreatedDate DATETIME NOT NULL)
CREATE TABLE contact(
contactId INT PRIMARY KEY IDENTITY(1,1),name varchar(50) null,email varchar(50) null,
subject varchar(200) null,Message VARCHAR(MAX)NULL,CreatedDate DATETIME NOT NULL)
CREATE TABLE Payment(
paymentId INT PRIMARY KEY IDENTITY(1,1),name varchar(50) null,cardno varchar(50) null,
expirydate varchar(50) null,cvvno INT NULL,Address Varchar (MAX) null,paymentmode VARCHAR(50)NULL)

CREATE TABLE Orders(
ordersdateid INT PRIMARY KEY IDENTITY(1,1),
orderno VARCHAR(max)null,PRODUCTId INT FOREIGN KEY REFERENCES PRODUCT (PRODUCTId) ON DELETE CASCADE NOT NULL,
Quantity INT NULL,userId INT FOREIGN KEY REFERENCES Users (userId) ON DELETE CASCADE NOT NULL,
Status VARCHAR(50)NULL,
paymentId INT FOREIGN KEY REFERENCES Payment (paymentId) ON DELETE CASCADE NOT NULL,
OrderDate Datetime NOT NULL,ISCANCEL BIT NOT NULL DEFAULT 0
)